### ISSUE TITLE
Add a skip navigation link at the top

### ISSUE THREAD

**Issue by joseluis** [andamira/medula#3]
I'd like it to be hidden by default, only shown when `tab` is pressed.

See the live example in this page, and very good discussion on alternative approaches and implementations:

- http://webaim.org/techniques/skipnav/
- [visually-hidden.css](https://gist.github.com/jonathantneal/bc41262b65bf673dfe62)

**Comment by joseluis** [comment]
Another good example, from github:
```HTML
<a href="#start-of-content" tabindex="1" class="accessibility-aid js-skip-to-content">Skip to content</a>
```

```CSS
.accessibility-aid {
height: 1px;
width: 1px;
clip: rect(1px, 1px, 1px, 1px);
overflow: hidden;
position: absolute;
margin: 0;
}
.accessibility-aid:focus {
height: auto;
width: auto;
clip: auto;
z-index: 1;
top: 0;
line-height: 49px;
padding: 0 10px;
background: #f5f5f5;
font-weight: bold;
text-decoration: none;
color: #333;
}
```
